# Dockerfile - Backend (Production)
FROM python:3.9-slim

WORKDIR /app

COPY backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app/

RUN python manage.py collectstatic --noinput  # Collecte des fichiers statiques pour la production

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "core.wsgi:application"]
